### ISSUE TITLE
Copy/paste menu not appear on iOS

### ISSUE THREAD

**Issue by flashman2** [retyui/react-native-confirmation-code-field#140]
On iOS 13.3, copy/paste menu does not appear with empty fields. If I enter some number/character then this system menu appears on double tap/long press as expected. Is there any workaround for this issue? I need to be able to copy/paste code using this functionality. Looking forward to any ideas.
![Code](https://user-images.githubusercontent.com/981169/85346968-ef7cd680-b518-11ea-81ab-5e34072892e2.gif)

**Comment by retyui** [comment]
> On iOS 13.3, copy/paste menu does not appear with empty fields

It is expected behavior. Let's have a look at these styles: 
https://github.com/retyui/react-native-confirmation-code-field/blob/ad626b02541138f2a7e3148237152f77b74a775f/src/CodeField.styles.tsx#L8-L14

> I need to be able to copy/paste code using this functionality. 

if you will press "Copy" will be copied all text value and "Paste" replace all text value


> Looking forward to any ideas.

You can create own button to copy 

---

To understand how real `<TextInput/>` looks like use, you can add: 

```diff
<CodeField
+  rootStyle={{
+    borderWidth: 1,
+    borderColor: 'red',
+  }}
+  textInputStyle={{
+    opacity: 0.7,
+    fontSize: 16,
+    borderWidth: 1,
+    borderColor: 'blue',
+  }}
/>;
```

**Comment by Symyon** [comment]
@retyui You mean expected behaviour to not show the copy option for an empty cell? That is understandable, what about paste text? The issue I'm having is not able to paste a code in the fields until I enter at least one value, same as the OP has posted above. Makes Pasting almost inutile. Do you think it can be fixed or is there a workaround you can suggest? A paste button can be done, but I would keep that option as the last resort. Thank you for the library!

**Comment by retyui** [comment]
@Symyon 

> You mean expected behaviour to not show the copy option for an empty cell? 

No. I meant that copy\paste menu will appear in the beginning on component all the time 

Please read first: https://github.com/retyui/react-native-confirmation-code-field#how-it-works And you will understand that I use a "viratual" TextInput under the Cells

**Comment by Symyon** [comment]
@retyui the issue here is not that it appears at the beginning of the component, it will not appear at all untill you write first character. So having an empty TextInput and cells makes it impossible to show the copy/paste menu. It does work by Ctrl+v or cmd+v , but on the device or emulator we can't use those shortcuts, we need the contextual.menu that isn't showing to be able to paste anything.
To be fair that is the issue off all the libraries that I tried and which use the same approach of hiding a TextInput. 

I was thinking of having a hidden character in the text input that will not show in the cells and we can render cells starting from position 1 and not 0. But the issue here is that if you'll copy the text from the component it will get the hidden character too.

**Comment by Symyon** [comment]
@flashman2 @retyui  Found the issue. TextInput has set caretHidden to true. That disables any copy/paste actions when TextInput is empty. Not sure why it is there as I can't see any issues in my case if removed or set to false (default). 
@retyui would you change that or if is there a reason to not, please let us know.

**Comment by retyui** [comment]
@Symyon @flashman2 

Fixed in [6.5.0](https://npmfs.com/compare/react-native-confirmation-code-field/6.4.0/6.5.0/)

**Comment by sprotymo** [comment]
the solution in 6.5.0 broken another feature described in
https://github.com/retyui/react-native-confirmation-code-field/issues/153

**Comment by retyui** [comment]
I reverted the fix [6.5.0](https://npmfs.com/compare/react-native-confirmation-code-field/6.4.0/6.5.0/) in the latest version because in affected https://github.com/retyui/react-native-confirmation-code-field/issues/153

```js

<CodeField
  // if copy/paste menu does not appear use
  caretHidden={false}
/>;
```

**Comment by elencho** [comment]
still an issue on some devices for example, Iphone SE(2nd) and Google Pixel
